apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-app-dev

bases:
  - ../../base

replicas:
  - name: sample-app
    count: 1

patchesStrategicMerge:
  - deployment.yaml

configMapGenerator:
  - name: app-config
    literals:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug