apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-tests
  namespace: tekton-pipelines
spec:
  params:
    - name: app-language
      type: string
      description: Programming language of the application
      default: "nodejs"
  workspaces:
    - name: source
      description: The workspace containing the source code
  steps:
    - name: test
      image: node:18-alpine
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e

        echo "Running tests..."

        # Install dependencies if package.json exists
        if [ -f "package.json" ]; then
          npm ci
          npm test
        elif [ -f "requirements.txt" ]; then
          pip install -r requirements.txt
          pytest
        elif [ -f "go.mod" ]; then
          go test ./...
        else
          echo "No test configuration found, skipping tests"
        fi

        echo "Tests completed successfully!"