apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-demo-app
  labels:
    app: tekton-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tekton-demo-app
  template:
    metadata:
      labels:
        app: tekton-demo-app
    spec:
      containers:
      - name: tekton-demo-app
        image: harbor.leorca.org/tekton-demo/tekton-demo:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5