apiVersion: v1
kind: Service
metadata:
  name: tekton-demo-app
  labels:
    app: tekton-demo-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: tekton-demo-app