apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-app-prod

bases:
  - ../../base

replicas:
  - name: sample-app
    count: 3

patchesStrategicMerge:
  - deployment.yaml

configMapGenerator:
  - name: app-config
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=warn