apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-app-staging

bases:
  - ../../base

replicas:
  - name: sample-app
    count: 2

patchesStrategicMerge:
  - deployment.yaml

configMapGenerator:
  - name: app-config
    literals:
      - ENVIRONMENT=staging
      - LOG_LEVEL=info